/**
 * Compatibility shim — Speech Intelligence lives in @wc/speech.
 */

export {
  AdaptiveSpeechGate,
  TranscriptStabilizer,
  NumberCollectionMode,
  assessTranscript,
  asksForContactNumber,
  normalizeDomainVocabulary,
  normalizeSpokenDigits,
  speechControlNote,
  transcriptEchoSimilarity,
  transcriptSimilarity,
  SpeechPipeline,
  defaultSpeechPipeline,
  EchoDetector,
  EntityRecognizer,
  PhraseCorrector,
  NoiseAnalyzer,
  SpeechConfidence,
  DomainVocabulary,
  NumberRecognizer,
  EmailRecognizer,
  CompanyRecognizer,
  NameRecognizer,
  NUMBER_COLLECTION_MIN_DIGITS,
  NUMBER_COLLECTION_MAX_DIGITS,
  MALAYALAM_SPEECH_RECOVERY,
  MALAYALAM_NUMBER_RECOVERY,
  INPUT_TRANSCRIPTION_CONFIG,
  type ConfidenceLevel,
  type BackgroundNoiseLevel,
  type CriticalSpeechField,
  type SpeechGateMode,
  type SpeechSensitivity,
  type NumberCollectionStage,
  type NumberCollectionSnapshot,
  type NumberCollectionTransition,
  type AcousticTurnMetrics,
  type SpeechGateResult,
  type PartialTranscriptObservation,
  type TranscriptStabilityResult,
  type DomainVocabularyResult,
  type TranscriptAssessment,
  type StabilizedSpeechTurn,
  type SpeechPipelineInput,
  type EntityBundle,
  type AssistantSpeechSnippet,
  type EchoDetectionResult,
} from "@wc/speech";
